# theme.toml template for a Hugo theme

name = "Bluey"
license = "MIT"
licenselink = "https://github.com/benrutter/bluey/blob/master/LICENSE"
description = "Bluey is a dark theme for hugo with a markdown-ish UI. It's forked from Archie."
homepage = "https://github.com/benrutter/bluey"
tags = ["blog","simple","responsive","minimal","tags","personal","clean","shortcodes"]
features = ["blog", "Clean and minimal", "Responsive", "Syntax highlighting",]
min_version = "0.41"
